[versions]
coroutines-version = "1.10.1"
netty-version = "4.1.116.Final"
scram-client-version = "3.1"
mockk-version = "1.13.14"
testcontainers-version = "1.20.4"
jdbc-postgres-version = "42.7.4"
logback-version = "1.5.16"

[libraries]
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines-version" }
netty-all = { group = "io.netty", name = "netty-all", version.ref = "netty-version" }
scram-client = { group = "com.ongres.scram", name = "scram-client", version.ref = "scram-client-version" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk-version" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers-version" }
jdbc-postgresql = { module = "org.postgresql:postgresql", version.ref = "jdbc-postgres-version" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-version" }
